FROM nvcr.io/nvidia/l4t-tensorflow:r32.5.0-tf2.3-py3

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y python3-opencv #unzip
#RUN pip3 install numpy scipy  matplotlib 
RUN pip3 install -U matplotlib tqdm #opencv-python

# Set the working directory
WORKDIR /work

# Add the data
ADD traffic_sign_seq_lowaccuracy.h5 /work
ADD frame203.jpg /work
#RUN unzip data.zip

# Add python-script
COPY Traffic_sign_classification-checkpoint-lowinference.py /work

ENTRYPOINT ["python3", "Traffic_sign_classification-checkpoint-lowinference.py"]

