#!/bin/bash

START=$(date +%s)
scp -i ~/.ssh/edge.pem data-20-200/* edgegateway@143.205.173.71:~/Documents/matching/framing/framing-200
END=$(date +%s)
#t1=$(date '+%s%N' --date="$1")
DIFF=$(( $END - $START ))
echo "It took $DIFF seconds"
#date +"%s.%3N" &&  \

START=$(date +%s)
scp -i ~/.ssh/edge.pem data-20-1500/* edgegateway@143.205.173.71:~/Documents/matching/framing/framing-1500
END=$(date +%s)
#t1=$(date '+%s%N' --date="$1")
DIFF=$(( $END - $START ))
echo "It took $DIFF seconds"

START=$(date +%s)
scp -i ~/.ssh/edge.pem data-20-3000/* edgegateway@143.205.173.71:~/Documents/matching/framing/framing-3000
END=$(date +%s)
#t1=$(date '+%s%N' --date="$1")
DIFF=$(( $END - $START ))
echo "It took $DIFF seconds"

START=$(date +%s)
scp -i ~/.ssh/edge.pem data-20-6500/* edgegateway@143.205.173.71:~/Documents/matching/framing/framing-6500
END=$(date +%s)
#t1=$(date '+%s%N' --date="$1")
DIFF=$(( $END - $START ))
echo "It took $DIFF seconds"

START=$(date +%s)
scp -i ~/.ssh/edge.pem data-20-20000/* edgegateway@143.205.173.71:~/Documents/matching/framing/framing-20000
END=$(date +%s)
#t1=$(date '+%s%N' --date="$1")
DIFF=$(( $END - $START ))
echo "It took $DIFF seconds"
exit
