FROM ubuntu

RUN apt-get update && apt-get install -y ffmpeg python3

# Set the working directory
WORKDIR /work

# Add python-script
COPY run-encoding.py /work
COPY 20.mp4 /work
COPY 20-20000.mp4 /work

ENTRYPOINT ["python3", "run-encoding.py", "x264"]
