#FROM ubuntu
FROM nvcr.io/nvidia/l4t-tensorflow:r32.5.0-tf2.3-py3

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y unzip python3-opencv #python3 python3-pip  python3-opencv
#RUN pip3 install numpy scipy  matplotlib 
RUN pip3 install -U pandas matplotlib tqdm #opencv-python # scikit-learn tqdm tensorflow keras


# Set the working directory
WORKDIR /work

# Add the data
ADD https://zenodo.org/records/11526387/files/data.zip?download=1 /work
RUN unzip data.zip

# Add python-script
COPY Traffic_sign_classification-checkpoint-highaccuracy.py /work

ENTRYPOINT ["python3", "Traffic_sign_classification-checkpoint-highaccuracy.py"]
